from grafos import Grafo

print("Grafo Lista Direcionado")
g = Grafo.generate(9, rep='lista', dirc=True)
g.add_A(0,1)
g.add_A(1,2)
g.add_A(1,4)
g.add_A(2,0)
g.add_A(2,3)
g.add_A(4,5)
g.add_A(5,1)
g.add_A(5,2)
g.add_A(5,3)
g.add_A(6,1)
g.add_A(6,4)
g.add_A(6,7)
g.add_A(7,6)
g.add_A(8,7)
g.to_string()
print(g.get_V())
print(g.get_A())
print(g.get_max_grau())
print(g.get_lacos())
print("--")
for x in Grafo.busca_dfs(g): print(x)
print("--")
for x in Grafo.busca_bfs(g): print(x)

print("Grafo Lista Não Direcionado")
g = Grafo.generate(5, rep='lista')
g.add_A(0,1)
g.add_A(0,2)
g.add_A(0,3)
g.add_A(1,3)
g.add_A(2,3)
g.add_A(3,4)
g.to_string()
print("--")
print(g.get_adj(1))
print(g.get_A())
print(g.get_max_grau())
print(g.is_eule())
print(g.has_eule_aberto())
print("-- Busca Dfs --")
for x in Grafo.busca_dfs(g): print(x)
print("-- Busca Bfs --")
for x in Grafo.busca_bfs(g): print(x)

print("Grafo Direcionado")
g = Grafo.generate(9, rep='matriz', dirc=True)
g.add_A(0,1)
g.add_A(1,2)
g.add_A(1,4)
g.add_A(2,0)
g.add_A(2,3)
g.add_A(4,5)
g.add_A(5,1)
g.add_A(5,2)
g.add_A(5,3)
g.add_A(6,1)
g.add_A(6,4)
g.add_A(6,7)
g.add_A(7,6)
g.add_A(8,7)
g.to_string()
print(g.get_V())
print(g.get_A())
print(g.get_max_grau())
print(g.get_lacos())
print("--")
for x in Grafo.busca_dfs(g): print(x)
print("--")
for x in Grafo.busca_bfs(g): print(x)

print("Grafo Matriz Não Direcionado")
g = Grafo.generate(5, rep='matriz')
g.add_A(0,1)
g.add_A(0,2)
g.add_A(0,3)
g.add_A(1,3)
g.add_A(2,3)
g.add_A(3,4)
g.to_string()
print("--")
print(g.get_adj(1))
print(g.get_A())
print(g.get_max_grau())
print(g.is_eule())
print(g.has_eule_aberto())
print("--")
for x in Grafo.busca_dfs(g): print(x)
print("--")
for x in Grafo.busca_bfs(g): print(x)